# Generated by Django 4.1.6 on 2023-03-03 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0003_alter_book_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='date_upload',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='ebook_link',
            field=models.URLField(null=True),
        ),
    ]
