# Generated by Django 4.1.6 on 2023-02-24 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0003_alter_customuser_is_staff'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
