# Generated by Django 4.1.6 on 2023-03-03 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0004_book_date_upload_book_ebook_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='thumbnail',
            field=models.URLField(null=True),
        ),
    ]
