# Generated by Django 4.1.6 on 2023-03-05 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0005_alter_book_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='my_review',
            field=models.TextField(null=True),
        ),
    ]
